[project]
name = "lib"
author = {name = "Polshkrev"}
description = "Library of single-file stb-like header files for c and c++."

[project.version]
minor = 21

[license]
type = "MIT"
path = "LICENSE"

[urls]
repository = "https://github.com/Polshkrev/lib"

[paths]
readme = "README.md"